spring.application.name=JobPortal-BE


server.port=8084


#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


#H2 DB Properties
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.url=jdbc:h2:file:~/Srikanth/SpringBoot2026/jobportaldb;AUTO_SERVER=true
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver

#Migrating to MySql properties
#Local Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/jobportal
spring.datasource.username=root
spring.datasource.password=adcb1234



spring.sql.init.schema-locations=classpath:sql/jobportal-schema.sql
#spring.sql.init.data-locations= optional:classpath:sql/jobportal-data.sql
spring.sql.init.data-locations= classpath:sql/jobportal-data.sql

#only for H2 to create tables and insert data
#spring.sql.init.mode=embedded

#for all databases, 2nd time onwards put it never
#spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none


spring.security.user.name=sree
spring.security.user.password=Sree@123
spring.security.user.roles=MANAGER, DEVELOPER