spring.application.name=JobPortal-BE


server.port=8084


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:h2:file:~/Srikanth/SpringBoot2026/jobportaldb;AUTO_SERVER=true
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver



spring.sql.init.schema-locations=classpath:sql/jobportal-schema.sql
#spring.sql.init.data-locations= optional:classpath:sql/jobportal-data.sql
spring.sql.init.data-locations= classpath:sql/jobportal-data.sql

#only for H2 to create tables and insert data
#spring.sql.init.mode=embedded

#for all databases, 2nd time onwards put it never
#spring.sql.init.mode=always

spring.jpa.show-sql=true